# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
image: naimgk/scientific-ubuntu
pipelines:
  branches:
    dev:
    - step:
        script:
          - ./configure --build=x64-ubuntu-gcc-atlas
          - make && make test
    - step:
        script:
          - ./configure --build=x64-ubuntu-gcc-openblas
          - make && make test

