# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
image: naimgk/ubuntu_gcc_gsl
pipelines:
  default:
    - step:
        script:
          - ./configure --build=linux-gcc
          - make
