name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get -y install build-essential libgsl-dev \
        libopenblas-dev liblapacke liblapacke-dev \
        libcfitsio-dev libfftw3-dev
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install NumPy
      run: pip install numpy
    - name: configure
      run: ./configure --build=github --enable-openmp
    - name: make
      run: make
    - name: make test
      run: make test
    # - name: cmake
    #   run: |
    #     mkdir myls-build-aux ; cd myls-build-aux
    #     cmake .. -DENABLE_MPI=OFF
    #     cmake --build .
    #     ctest .
