name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get -y install build-essential libgsl-dev \
        libopenblas-base libopenblas-dev liblapacke liblapacke-dev \
        libcfitsio-dev libfftw3-dev
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install NumPy
      run: pip install numpy
    - name: configure
      run: ./configure --enable-openmp CBLAS_DIR=/opt/openblas
    - name: make
      run: make
    - name: make test
      run: make test
